### ISSUE TITLE
tls-server-name should be "kubernetes"

### ISSUE THREAD

**Issue by starbops** [inlets/docs.inlets.dev#1]
## Proposed change

In "Tutorial: Expose a local Kubernetes API Server", there is a section shows us how to modify kubeconfig file with the new endpoint. The current value (k3s.example.com) of `tls-server-name` is misleading. It should be `kubernetes` or one of the `kubectl cluster-info` suggests:  kind-control-plane, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, localhost.

## Context

I created a cluster using KinD on my Ubuntu machine. Following the tutorial, everything goes fine. However, if the value of `tls-server-name` is configured to the subdomain of the public VM's IP, kubectl will be unable to connect to the private k8s cluster due to certificate issue.

## Your Environment

* `inlets-pro version`: 0.9.3-rc1

* Are you using inlets? Yes

* Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04

**Comment by alexellis** [comment]
Thank you. Could you send a quick PR for this?

**Comment by starbops** [comment]
Fixed.
