### ISSUE TITLE
The license is base64 encoded twice in docs/uplink/create-tunnels.md

### ISSUE THREAD

**Issue by c0dyhi11** [inlets/docs.inlets.dev#22]
## Proposed change
The $LICENSE is base64 encoded when you run the command as is.

But `--from-literal` base64 encodes the license again, so you get the following error from your tunnel POD: 
```
License format may be invalid for inlets-uplink
```

Adding `base64 -d` to the `kubectl get secret` command solved this.

## Context
Following the documentation for the first time I ran into this issue.

## My Environment
Google GKE Cluster Version: 1.26.1-gke.1500
* `inlets-uplink version`
  * Chart: inlets-uplink-provider-0.2.7
  * App Version: 1.0

* Are you using inlets?
  * Yes

* Operating System and version (e.g. Linux, Windows, MacOS):
  * Client OS is Ubuntu 20.04 Server
  * K8s OS is Google COS (Container Optimized Linux)

**Comment by alexellis** [comment]
Thanks for this @c0dyhi11 👍
